name = "SparseMaxSR"
uuid = "67da26f7-3efd-406f-8ecf-6571d1bf31c7"
license = "MIT"
authors = ["Alberto Quaini <alberto91quaini@gmail.com>"]
version = "0.2.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
COSMO = "1e616198-aa4e-51ec-90a2-23f7fbd31d8d"
Clarabel = "61c947e1-3e6d-4ee4-985a-eec8c727bd6e"
SCS = "c946c3f1-0d1f-5ce8-9c59-874cb05f43e9"

[extensions]
SparseMaxSRClarabelExt     = ["Clarabel"]
SparseMaxSRCOSMOExt        = ["COSMO"]
SparseMaxSRSCExt           = ["SCS"]
SparseMaxSRCPLEXExt        = ["CPLEX"]
SparseMaxSRMosekToolsExt   = ["MosekTools"]


[compat]
julia = "1.10, 1.11"
Combinatorics = "1"
JuMP = "1"
MathOptInterface = "1"
# Optional solvers (if installed)
COSMO = "0.8"
Clarabel = "0.8"
SCS = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
